=== joabj/XML-Address-Book/Addresses.dtd
<!ELEMENT document (contact)*>
  <!ELEMENT contact (name, address, info, other)*>
  <!ELEMENT name (firstname, lastname)>
  <!ELEMENT firstname (#PCDATA)>
  <!ELEMENT lastname (#PCDATA)>
  <!ELEMENT address (street1, street2, city, state, zip)>
  <!ELEMENT street1 (#PCDATA)> 
  <!ELEMENT street2 (#PCDATA)>
  <!ELEMENT city (#PCDATA)>
  <!ELEMENT state (#PCDATA)>
  <!ELEMENT zip (#PCDATA)>
  <!ELEMENT info (hphone, wphone, cphone, wemail, hemail1, hemail2, hemail3, website)>
  <!ELEMENT hphone (#PCDATA)>
  <!ELEMENT wphone (#PCDATA)>
  <!ELEMENT cphone (#PCDATA)>
  <!ELEMENT wemail (#PCDATA)>
  <!ELEMENT hemail1 (#PCDATA)>
  <!ELEMENT hemail2 (#PCDATA)>
  <!ELEMENT hemail3 (#PCDATA)>
  <!ELEMENT website (#PCDATA)>
  <!ELEMENT other (#PCDATA)>
	<!ATTLIST contact active ( yes |  no ) #IMPLIED>

=== joabj/XML-Address-Book/Addresses.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="addresses.css"?>
<!--Uncomment this if you plan to use the DTD instead of the schema. you must use on of the other: <!DOCTYPE document SYSTEM "addresses.dtd"> Take out stuff in document decalration just below starting with xmlns and to the end of the bracket-->
<document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="addresses.xsd">
	<contact active="no">
		<name>
			<firstname>First name goes here</firstname>
			<lastname>Last Name here</lastname>
		</name>
		<address>
			<street1>Street address here</street1>
			<street2>More street stuff here</street2>
			<city>City Here </city>
			<state> State </state>
			<zip> zip </zip>
		</address>
		<info>
			<hphone> Home phone </hphone>
			<wphone> Work phone </wphone>
			<cphone> Cell phone</cphone>
			<wemail> Work Email </wemail>
			<hemail1> Home email</hemail1>
			<hemail2/>
			<hemail3/>
			<website> Web site</website>
		</info>
		<other> Whatever addiitonal info goes here 
</other>
	</contact>
</document>
